"""empty message

Revision ID: 284c1c0b04b7
Revises: b7634bfb9126
Create Date: 2022-01-17 13:41:01.098370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284c1c0b04b7'
down_revision = 'b7634bfb9126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
